spring.application.name=activity1

spring.datasource.url=jdbc:mysql://localhost:3307/L23Y19W01
spring.datasource.username=L23Y19W01
spring.datasource.password=aaron123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true